// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	EnvironmentVariables string
	Hoge                 string
	Todo                 string
	User                 string
}{
	EnvironmentVariables: "environment_variables",
	Hoge:                 "hoge",
	Todo:                 "todo",
	User:                 "user",
}
