// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	PrismaMigrations string
	Env              string
	EnvSetting       string
	Post             string
	Stage            string
	Task             string
	Todo             string
	User             string
}{
	PrismaMigrations: "_prisma_migrations",
	Env:              "env",
	EnvSetting:       "env_setting",
	Post:             "post",
	Stage:            "stage",
	Task:             "task",
	Todo:             "todo",
	User:             "user",
}
