// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("EnvironmentVariables", testEnvironmentVariablesUpsert)

	t.Run("Hoges", testHogesUpsert)

	t.Run("Todos", testTodosUpsert)

	t.Run("Users", testUsersUpsert)
}
