// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("PrismaMigrations", testPrismaMigrationsUpsert)

	t.Run("Envs", testEnvsUpsert)

	t.Run("EnvSettings", testEnvSettingsUpsert)

	t.Run("Posts", testPostsUpsert)

	t.Run("Stages", testStagesUpsert)

	t.Run("Tasks", testTasksUpsert)

	t.Run("Todos", testTodosUpsert)

	t.Run("Users", testUsersUpsert)
}
